services:
  backend:
    build:
      context: ./server-side
      dockerfile: Dockerfile
    image: hapejoy/crpm-server:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - app-network
    restart: unless-stopped

  status21:
    build:
      context: ./client-side/status21-app
      dockerfile: Dockerfile
      # Build-time API used by Next.js server (internal Docker network hostname)
      args:
        API_URL: http://backend:3000
    image: hapejoy/status21-client:latest
    ports:
      - "8080:8080"
    environment:
      # Client-side API should be relative so browser calls go through reverse-proxy
      - API_URL=/api
      - PORT=8080
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  crpm-aging:
    build:
      context: ./client-side/crpm-aging
      dockerfile: Dockerfile
      # Build-time API for the static app; use relative '/api' so proxy handles routing
      args:
        VITE_API_BASE_URL: /api
    image: hapejoy/crpm-aging-client:latest
    ports:
      - "8081:80"
    environment:
      - VITE_API_BASE_URL=/api
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    image: hapejoy/reverse-proxy:latest
    ports:
      - "80:80"
    depends_on:
      - status21
      - crpm-aging
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge