services:
  backend:
    image: hapejoy/crpm-server:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - app-network
    restart: always

  frontend:
    image: hapejoy/cmez-client:latest
    # Remove or comment out the ports section below if you only want access via Nginx
    # ports:
    #   - "8080:8080"
    environment:
      PORT: 8080
      API_URL: http://backend:3000
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

  nginx:
    image: hapejoy/cmez-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge