services:
  backend:
    build:
      context: ./server-side
      dockerfile: Dockerfile
    image: hapejoy/crpm-server:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - app-network
    restart: unless-stopped

  status21:
    build:
      context: ./client-side/status21-app
      dockerfile: Dockerfile
      args:
        API_URL: http://backend:3000
    image: hapejoy/status21-client:latest
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://backend:3000
      - PORT=8080
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  crpm-aging:
    build:
      context: ./client-side/crpm-aging
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://backend:3000
    image: hapejoy/crpm-aging-client:latest
    ports:
      - "8081:80"
    environment:
      - VITE_API_BASE_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    image: hapejoy/reverse-proxy:latest
    ports:
      - "80:80"
    depends_on:
      - status21
      - crpm-aging
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge